# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-Google
version:      0.22
version_from: Google.pm
installdirs:  site
requires:
    Net::Google:                   0.52
    Test::More:                    0.01
    WWW::Search:                   2.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
